/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1dde0675-787e-4284-af35-7be1da296f19",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gDqi5AtRS",
    "aws_user_pools_web_client_id": "65d6it0jqp1bpekftpfflnk24o",
    "oauth": {}
};


export default awsmobile;
