/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3808e251-18fc-4f26-a9c8-c9b2764a5f84",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Td5UTIuV4",
    "aws_user_pools_web_client_id": "74l1da1n5agc9l065kqlrtf9n3",
    "oauth": {}
};


export default awsmobile;
