/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:03ae6fda-cda8-40f0-9dda-47258d6dd813",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_AAxvlZKRe",
    "aws_user_pools_web_client_id": "41q3sk9iolkg5n8agqf2heiqff",
    "oauth": {}
};


export default awsmobile;
